name: GitHub CI/CD

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.16.1 ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

      - name: Archive coverage artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@master
        with:
          name: rxjs-common-coverage
          path: ./coverage

      - name: Linter
        run: npm run lint

      - name: Build
        run: npm run build
        env:
          CI: true

      - name: Archive production artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@master
        with:
          name: rxjs-common
          path: ./dist

  coverall:
    name: Coverall
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.16.1 ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: rxjs-common-coverage
          path: ./coverage

      - name: Send coverage to Coverall
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info

  deploy-paddls:
    name: Deploy @paddls
    needs: build
    if: "github.ref == 'refs/heads/master' && contains(github.event.head_commit.message, 'release: v')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.16.1 ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: rxjs-common
          path: ./dist

      - name: Publish @paddls
        uses: pascalgn/npm-publish-action@1.3.9
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          commit_pattern: "^release: v(\\S+)"
          publish_args: "--access public"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN_PADDLS }}

  deploy-witty-services:
    name: Deploy @witty-services
    needs: build
    if: "github.ref == 'refs/heads/master' && contains(github.event.head_commit.message, 'release: v')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.16.1 ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: rxjs-common
          path: ./dist

      - name: PrePublish @witty-services
        uses: jossef/action-set-json-field@v1
        with:
          file: package.json
          field: name
          value: "@witty-services/rxjs-common"

      - name: Publish @witty-services
        uses: pascalgn/npm-publish-action@1.3.9
        with:
          commit_pattern: "^release: v(\\S+)"
          publish_args: "--access public"
          create_tag: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN_PADDLS }}
